-- Supabase schema for uploaded documents
-- Run this in your Supabase SQL editor

create table if not exists public.uploaded_documents (
  id uuid generated by default as identity primary key,
  user_id uuid not null,
  filename text not null,
  upload_date timestamptz default now(),
  rag_document_id text,
  chunks_indexed integer,
  metadata jsonb,
  created_at timestamptz default now()
);

-- Index by user_id for fast queries
create index if not exists idx_uploaded_documents_user_id on public.uploaded_documents (user_id);
